doc/erc-20x-draft.md

Need a public repo we can link to for this draft.  This repo seems as good as any.

doc: add erc-20x draft

---

package-lock.json
package.json

chore(release): version bump

---

contracts/StringAddressUtils.sol
contracts/StringBytesUtils.sol
test/Util.js

fix(String Utils): improving utils based on audit report

---

scripts/constAddressDeployer.js
scripts/create3Deployer.js

If a number is passed to the function, the returned value will be the same. This PR ensures key used here is always a string.

chore: ensure key to be a string

---

contracts/express/ExpressExecutable.sol
contracts/express/ExpressProxyDeployer.sol
package-lock.json
package.json

fix(ExpressProxyDeployer): fixing ExpressProxy constructor params

---

contracts/express/ExpressExecutable.sol
contracts/express/ExpressProxyDeployer.sol
contracts/interfaces/IExpressProxyDeployer.sol
contracts/upgradable/BaseProxy.sol
contracts/upgradable/FixedProxy.sol
contracts/upgradable/InitProxy.sol
contracts/upgradable/Proxy.sol
package-lock.json
package.json

feat: renamed FixedProxy

---

contracts/test/proxy/DifferentProxyImplementation.sol
contracts/test/proxy/FixedImplementation.sol
contracts/test/proxy/InvalidProxyImplementation.sol
contracts/test/proxy/InvalidSetupProxyImplementation.sol
contracts/test/proxy/ProxyImplementation.sol
contracts/test/proxy/TestProxy.sol
contracts/upgradable/Proxy.sol
test/GMPE.js
test/Proxy.js

Added test coverage for different proxy contracts corresponding to test cases on notion. Feel free to edit or suggest additional test cases.

test: proxy test coverage

---

contracts/deploy/Create3.sol
contracts/test/proxy/InvalidSetupProxyImplementation.sol
contracts/upgradable/Upgradable.sol
contracts/utils/ContractAddress.sol
test/Create3Deployer.js
test/Upgradable.js

fix(Create3): checking for empty account with native ether balance

---

contracts/express/ExpressExecutable.sol
contracts/express/ExpressProxy.sol
contracts/express/ExpressProxyDeployer.sol
contracts/express/ExpressRegistry.sol
contracts/express/ExpressService.sol
contracts/express/ExpressServiceProxy.sol

NatSpec documentation for GMP Express contracts.

feat: natspec for express contracts

---

.solhint.json
contracts/deploy/ConstAddressDeployer.sol
contracts/deploy/Create3.sol
contracts/deploy/Create3Deployer.sol
contracts/express/ExpressProxy.sol
contracts/express/ExpressProxyDeployer.sol
contracts/test/ERC20.sol
contracts/test/ERC20MintableBurnable.sol
contracts/test/ERC20MintableBurnableInit.sol
contracts/test/ERC721MintableBurnable.sol
contracts/test/MockDepositReceiver.sol
contracts/test/MockGasService.sol
contracts/test/MockGateway.sol
contracts/test/ProxyTest.sol
contracts/test/UpgradableTest.sol
contracts/test/UtilTest.sol
contracts/test/gmp/DestinationChainTokenSwapper.sol
contracts/upgradable/BaseProxy.sol
contracts/upgradable/FinalProxy.sol
contracts/upgradable/FixedProxy.sol
contracts/upgradable/InitProxy.sol
contracts/upgradable/Proxy.sol
contracts/upgradable/Upgradable.sol
contracts/utils/Bytes32String.sol
contracts/utils/Ownable.sol
contracts/utils/SafeTransfer.sol
test/ConstAddressDeployer.js
test/utils.js

NatSpec documentation for all contracts within the deploy and upgradable folders.

feat: natspec docs for deploy and upgradable contracts

---

contracts/utils/Operators.sol
scripts/constAddressDeployer.js
scripts/create3Deployer.js
test/Operators.js

PR to add a receive method to the Operators contract.

feat: add receive to operators

---

.gitignore
contracts/test/TestOperators.sol
hardhat.config.js
package-lock.json
package.json
test/Operators.js
test/utils.js

PR to allow running uint tests against live testnets.

feat: run tests against live testnets

---

contracts/utils/Operators.sol
package.json
test/Operators.js

PR to pass the initial owner of Operators as a constructor arg.

fix: initial owner as constructor arg

---

contracts/interfaces/IContractExecutor.sol
contracts/interfaces/IExecute.sol
contracts/interfaces/IOperators.sol
contracts/utils/Operators.sol
test/Operators.js

feat: execute interface

---

.github/workflows/publish-to-npm.yaml
.gitignore
package-lock.json
package.json

build(npm): building interfaces and version bump

---

contracts/deploy/Create3Deployer.sol
test/Create3Deployer.js

feat(Create3Deployer): passing native value for deployment

---

contracts/governance/Multisig.sol
contracts/governance/MultisigBase.sol
contracts/interfaces/IMultisig.sol
contracts/utils/Caller.sol
test/Multisig.js

feat(Multisig): withdraw functionality

---

contracts/interfaces/IContractIdentifier.sol
contracts/interfaces/IUpgradable.sol
contracts/upgradable/BaseProxy.sol
contracts/upgradable/FinalProxy.sol
contracts/upgradable/FixedProxy.sol
contracts/upgradable/InitProxy.sol
contracts/upgradable/Proxy.sol

fix(Proxy): checking contractId for final and fixed proxies

---

.gitignore
package.json
scripts/constAddressDeployer.js
scripts/create3Deployer.js
scripts/upgradable.js

build(package): removing the dist folder

---

contracts/governance/DESIGN.md

docs(Governance): design docs

---

contracts/test/UpgradableTest.sol
contracts/upgradable/Upgradable.sol
contracts/utils/Ownable.sol
test/Upgradable.js

PR to remove the owner constructor arg from Upgradable.sol

fix(Upgradable): remove owner constructor arg

---

contracts/libs/AddressString.sol
test/upgradable/Proxy.js

PR for bytecode preservation tests for proxy contracts.

feat(Proxy): bytecode tests

---

.github/workflows/publish-bytecode.yaml
.github/workflows/publish-to-npm.yaml
package-lock.json
package.json

ci(publish): publishing bytecode on release

---

package-lock.json
package.json

chore: remove unused openzeppelin dep

---

contracts/governance/AxelarServiceGovernance.sol
contracts/interfaces/IAxelarServiceGovernance.sol
contracts/interfaces/IInterchainGovernance.sol
test/governance/AxelarServiceGovernance.js

PR for IInterchainGovernance to inherit ITimeLock and to add a function to AxelarServiceGovernance to check whether or not a multisig proposal has been approved.

feat(IInterchainGovernance): inherit ITimeLock

---

.gitignore
contracts/deploy/Create2.sol
contracts/deploy/Create3.sol
contracts/deploy/Deployer.sol
contracts/express/AxelarValuedExpressExecutable.sol
contracts/governance/InterchainGovernance.sol
contracts/governance/Multisig.sol
contracts/libs/SafeNativeTransfer.sol
contracts/libs/SafeTransfer.sol
contracts/test/express/TestAxelarValuedExpressExecutable.sol
package-lock.json
package.json
test/deploy/ConstAddressDeployer.js
test/deploy/Create2Deployer.js
test/deploy/Create3Deployer.js
test/upgradable/Proxy.js

refactor(SafeNativeTransfer): splitting into a separate file

---

contracts/test/gmp/DestinationChainReceiver.sol
contracts/test/gmp/SourceChainSender.sol
contracts/test/governance/TestInterchainGovernance.sol
contracts/test/libs/LibsTest.sol
contracts/test/libs/NoFallback.sol
contracts/test/upgradable/CallInitProxy.sol
contracts/test/upgradable/InvalidUpgradableTest.sol
contracts/test/upgradable/TestFinalProxy.sol
contracts/test/upgradable/TestFixedProxy.sol
contracts/test/upgradable/TestInitProxy.sol
contracts/test/upgradable/UpgradableTest.sol
test/GMP/GMP.js
test/GMP/GMPE.js
test/deploy/Create2Deployer.js
test/governance/InterchainGovernance.js
test/upgradable/Proxy.js
test/upgradable/Upgradable.js
test/utils/Util.js

PR for improved unit test coverage as per [AXE-1147](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?modal=detail&selectedIssue=AXE-1147)
[AXE-1147]: https://axelarnetwork.atlassian.net/browse/AXE-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: full test coverage

---

DESIGN.md
contracts/governance/AxelarServiceGovernance.sol
contracts/governance/BaseMultisig.sol
contracts/test/gmp/DestinationChainReceiver.sol
contracts/test/gmp/SourceChainSender.sol
contracts/test/governance/TestBaseMultiSig.sol
contracts/test/governance/TestInterchainGovernance.sol
contracts/test/libs/LibsTest.sol
contracts/test/libs/NoFallback.sol
contracts/test/upgradable/CallInitProxy.sol
contracts/test/upgradable/InvalidUpgradableTest.sol
contracts/test/upgradable/TestFinalProxy.sol
contracts/test/upgradable/TestFixedProxy.sol
contracts/test/upgradable/TestInitProxy.sol
contracts/test/upgradable/UpgradableTest.sol
package-lock.json
package.json
test/GMP/GMP.js
test/GMP/GMPE.js
test/deploy/Create2Deployer.js
test/governance/AxelarServiceGovernance.js
test/governance/BaseMultisig.js
test/governance/InterchainGovernance.js
test/upgradable/Proxy.js
test/upgradable/Upgradable.js
test/utils/Util.js

chore: cherry pick multisig vote reset improvement

---

hardhat.config.js
package-lock.json
package.json

Replaced `axelar-contracts-deployment` dependency with [axelar-chains-config](https://github.com/axelarnetwork/axelar-contract-deployments/tree/main/axelar-chains-config)

chore: use axelar-chains-config

---

hardhat.config.js
package-lock.json
package.json

chore: use axelar-chains-config (#88)

---

.github/CODEOWNERS

chore: cleanup codeowners

---

contracts/governance/BaseMultisig.sol
contracts/interfaces/IBaseMultisig.sol
test/governance/BaseMultisig.js

[AXE-1987](https://axelarnetwork.atlassian.net/browse/AXE-1987)
[AXE-1987]: https://axelarnetwork.atlassian.net/browse/AXE-1987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(BaseMultisig): emit MultisigVoted event

---

contracts/governance/BaseMultisig.sol
contracts/interfaces/IBaseMultisig.sol
test/governance/BaseMultisig.js

feat(BaseMultisig): emit MultisigVoted event (#93)

---

package-lock.json
package.json

chore: bump version (#95)

---

scripts/create2Deployer.js
scripts/create3Deployer.js

[AXE-2164]
[AXE-2164]: https://axelarnetwork.atlassian.net/browse/AXE-2164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: allow configuring confirmations for contract deployments

---

contracts/interfaces/IAxelarGateway.sol

[AXE-2316]
[AXE-2316]: https://axelarnetwork.atlassian.net/browse/AXE-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(gateway): add ContractCallExecuted event

---

contracts/express/AxelarValuedExpressExecutable.sol

fix(ValuedExpress): interface inheritance

---

package-lock.json
package.json
scripts/flatten-contracts.sh

- Use same flatten script as cgp solidity

chore: update flatten script

---

contracts/test/utils/TestMulticall.sol
contracts/test/utils/TestPausable.sol
contracts/test/utils/TestReentrancyGuard.sol
test/utils/Multicall.js
test/utils/Pausable.js
test/utils/ReentrancyGuard.js

Fix minor test coverage gaps as per [AXE-2452](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2452)
[AXE-2452]: https://axelarnetwork.atlassian.net/browse/AXE-2452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: minor test coverage gaps

---

contracts/test/utils/TestInterchainAddressTracker.sol
contracts/upgradable/Implementation.sol
contracts/upgradable/Upgradable.sol
contracts/utils/InterchainAddressTracker.sol
package-lock.json
package.json
test/utils/InterchainAddressTracker.js

fix(Upgradable): improved contract id verification

---

.github/workflows/slither.yml
hardhat.config.js
slither.config.json
test/governance/AxelarServiceGovernance.js
test/governance/InterchainGovernance.js

feat: fix proxy contract compiler settings (#118)

---

.github/workflows/test.yaml
README.md
hardhat.config.js
package-lock.json
package.json
test/GMP/GMPE.js
test/deploy/Create2Deployer.js
test/deploy/Create3Deployer.js
test/governance/InterchainGovernance.js

feat: add hardhat utils (#119)

---

contracts/executable/AxelarGMPExecutable.sol
contracts/executable/AxelarGMPExecutableWithToken.sol
contracts/interfaces/IAxelarGMPExecutable.sol
contracts/interfaces/IAxelarGMPExecutableWithToken.sol
contracts/interfaces/IAxelarGMPGateway.sol
contracts/interfaces/IAxelarGMPGatewayWithToken.sol
contracts/test/executable/GMPExecutableTest.sol
contracts/test/executable/GMPExecutableWithTokenTest.sol
test/executable/GMPExecutable.js
test/executable/GMPExecutableWithToken.js

feat(GMP Gateway): new GMP Gateway interface (#117)

---

.github/workflows/codecov.yaml

Integrate codecov as per [AXE-3415](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-3415)
[AXE-3415]: https://axelarnetwork.atlassian.net/browse/AXE-3415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add codecov action

---

.github/workflows/conventional-commits.yaml
.github/workflows/lint.yaml
.github/workflows/slither.yaml
.github/workflows/test.yaml

Add cancel in progress to workflows

feat: add cancel in progress to workflows

---

.solhint.json
.solhintignore
contracts/governance/AxelarServiceGovernance.sol
contracts/interfaces/IAxelarServiceGovernance.sol
contracts/interfaces/IInterchainAddressTracker.sol
contracts/test/gmp/ExecutableSample.sol
contracts/test/upgradable/TestProxy.sol
package-lock.json
package.json
test/governance/AxelarServiceGovernance.js

Update hardhat to `v2.22.2`. This requires dropping node `v16` support as well.

fix(hardhat): update hardhat dep

---

contracts/gateway/AxelarAmplifierAuth.sol
contracts/gateway/AxelarAmplifierGateway.sol
contracts/gateway/BaseAmplifierGateway.sol
contracts/governance/BaseWeightedMultisig.sol
contracts/governance/InterchainMultisig.sol
contracts/interfaces/IAxelarAmplifierGateway.sol
contracts/interfaces/IAxelarAmplifierGatewayAuth.sol
contracts/interfaces/IBaseAmplifierGateway.sol
contracts/interfaces/IBaseWeightedMultisig.sol
contracts/interfaces/IInterchainMultisig.sol
contracts/test/governance/TestBaseWeightedMultisig.sol
hardhat.config.js
scripts/utils.js
test/gateway/AxelarAmplifierAuth.js
test/gateway/AxelarAmplifierGateway.js
test/governance/AxelarServiceGovernance.js
test/governance/BaseWeightedMultisig.js

[AXE-3708]
[AXE-3708]: https://axelarnetwork.atlassian.net/browse/AXE-3708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(amplifier)!: inherit weighted multisig in amplifier gateway

---

.github/workflows/publish-bytecode.yaml
hardhat.config.js
package-lock.json
package.json

ci: fix bytecode publish action

---

contracts/gateway/INTEGRATION.md
contracts/gateway/README.md

Added a Gateway integration doc

docs(amplifier): add amplifier gateway docs

---

contracts/gateway/BaseAmplifierGateway.sol
contracts/gateway/INTEGRATION.md
contracts/interfaces/IBaseAmplifierGateway.sol
test/gateway/AxelarAmplifierGateway.js

[AXE-3977]
[AXE-3977]: https://axelarnetwork.atlassian.net/browse/AXE-3977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(amplifier)!: rename gateway approval and executed events

---

contracts/gateway/AxelarAmplifierGateway.sol
contracts/gateway/INTEGRATION.md
contracts/governance/BaseWeightedMultisig.sol
contracts/interfaces/IAxelarAmplifierGateway.sol
contracts/interfaces/IBaseWeightedMultisig.sol
test/gateway/AxelarAmplifierGateway.js
test/governance/BaseWeightedMultisig.js
test/governance/InterchainMultisig.js

[AXE-3856]
[AXE-3856]: https://axelarnetwork.atlassian.net/browse/AXE-3856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

perf(amplifier)!: prevent auth contract from rotating to duplicate signers

---

contracts/gateway/INTEGRATION.md
contracts/types/AmplifierGatewayTypes.sol
test/gateway/AxelarAmplifierGateway.js
test/governance/BaseWeightedMultisig.js

[AXE-3992]
[AXE-3992]: https://axelarnetwork.atlassian.net/browse/AXE-3992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(amplifier): re-order message id and source chain fields

---

test/gateway/AxelarAmplifierGateway.js

https://axelarnetwork.atlassian.net/browse/AXE-3978

chore: add gasOptions during gateway deployment in test

---

.changeset/tiny-eyes-provide.md
contracts/governance/BaseWeightedMultisig.sol
contracts/interfaces/IBaseWeightedMultisig.sol
test/governance/BaseWeightedMultisig.js

[AXE-6298](https://axelarnetwork.atlassian.net/browse/AXE-6298)
[AXE-6298]: https://axelarnetwork.atlassian.net/browse/AXE-6298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(gateway): update signer hash to signers hash

---

contracts/utils/InterchainAddressTracker.sol

[AXE-6479](https://axelarnetwork.atlassian.net/browse/AXE-6479)
[AXE-6479]: https://axelarnetwork.atlassian.net/browse/AXE-6479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: change chain name function to public

---

.changeset/tidy-jeans-greet.md
.github/workflows/release.yaml

- Update the way how the package version is getting retrieved

ci: update the way the package version is being retrieved
